server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: keystore.p12
    key-store-password: VeryStrongPasswd
    key-alias: jetty

spring:
  security:
    require-ssl: true
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1229000067224783
            client-secret: 21108f17d4a83043400faa974b1bdb8b
          github:
            client-id: e599b5fa6294b5defea3
            client-secret: 66c12b288195221958d5de39f47d731f8229ab16